version: '3'
services:
  nginx:
    build:
      context: ./nginx
    container_name: yii2_ngx_nginx
    image: jdsteam/yii2_ngx_nginx:1.0
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/html
    depends_on:
      - api
      - frontend
      - backend
      - memcached
    ports:
      - 80:80
      - 443:443

  api:
    build:
      context: ./api
    container_name: yii2_ngx_api
    image: jdsteam/yii2_ngx_api:1.0
    networks:
      - internal
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./api:/srv
      - /srv/vendor

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: yii2_ngx_backend
    image: jdsteam/yii2_ngx_backend:1.0
    depends_on:
      - api
    networks:
      - internal
    volumes:
      - ./backend/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: yii2_ngx_frontend
    image: jdsteam/yii2_ngx_frontend:1.0
    depends_on:
      - api
    networks:
      - internal
    volumes:
      - ./frontend/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/app

  database:
    image: mysql:5.7
    container_name: yii2_ngx_database
    networks:
      - internal
    ports:
      - 3306:3306
    env_file:
      - .env

  memcached:
    container_name: yii2_ngx_memcached
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge