version: '3'
services:
  api:
    # build:
    #   context: ./api
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend-api:${VERSION}
    networks:
      - internal
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      # - ./api:/srv
      # - /srv/vendor
      - vol_storage:/srv/web/storage
    ports:
      - 81:80

  queue:
    # build:
    #   context: ./api
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend-api:${VERSION}
    networks:
      - internal
    depends_on:
      - database
      - api
    env_file:
      - .env
    volumes:
      # - ./api:/srv
      # - /srv/vendor
      - vol_storage:/srv/web/storage
    restart: on-failure
    command: ['bash','-c','/srv/yii queue/listen --verbose']

  memcached:
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  vol_storage:
    driver: local
  vol_mysql_data:
    driver: local