version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.test-api
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-nginx:${CI_COMMIT_REF_SLUG}
    networks:
      - internal
    volumes:
      - ./nginx:/etc/nginx/html
    depends_on:
      - api
      - memcached
    ports:
      - 80:80
      - 443:443

  api:
    build:
      context: ./api
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-api:${CI_COMMIT_REF_SLUG}
    networks:
      - internal
    depends_on:
      - database
    env_file:
      - .env-dev
    volumes:
      - ./api:/srv
      - /srv/vendor

  database:
    image: mysql:5.7
    networks:
      - internal
    env_file:
      - .env-dev

  memcached:
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge
