version: '3'
services:
  nginx:
    image: jdsteam/sapawarga-nginx:1.0
    networks:
      - internal
    depends_on:
      - api
      - frontend
      - backend
      - memcached
    ports:
      - 80:80
      - 443:443

  api:
    image: jdsteam/sapawarga-api:1.0
    networks:
      - internal
    env_file:
      - .env

  backend:
    image: jdsteam/sapawarga-backend:1.0
    depends_on:
      - api
    networks:
      - internal

  frontend:
    image: jdsteam/sapawarga-frontend:1.0
    depends_on:
      - api
    networks:
      - internal

  memcached:
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge