version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: jdsteam/sapawarga-nginx:1.0
    networks:
      - internal
    volumes:
      - ./nginx:/etc/nginx/html
    depends_on:
      - api
      - frontend
      - backend
      - memcached
    ports:
      - 80:80
      - 443:443

  api:
    build:
      context: ./api
    image: jdsteam/sapawarga-api:1.0
    networks:
      - internal
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./api:/srv

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jdsteam/sapawarga-backend:1.0
    depends_on:
      - api
    networks:
      - internal
    # volumes:
    #   - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: jdsteam/sapawarga-frontend:1.0
    depends_on:
      - api
    networks:
      - internal
    # volumes:
    #   - ./frontend:/app

  database:
    image: mysql:5.7
    networks:
      - internal
    ports:
      - 3306:3306
    env_file:
      - .env

  memcached:
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge
