version: '3'
services:
  api:
    # build:
    #   context: ./api
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend-api:latest
    networks:
      - internal
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      # - ./api:/srv
      # - /srv/vendor
      - vol_storage:/srv/web/storage
    ports:
      - 81:80

  database:
    image: mysql:5.7
    networks:
      - internal
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - vol_mysql_data:/var/lib/mysql

  memcached:
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  vol_storage:
    driver: local
  vol_mysql_data:
    driver: local