version: '3'
services:
  nginx:
    build:
      context: ./nginx
    image: jdsteam/sapawarga:1.0
    networks:
      - internal
    volumes:
      - ./nginx:/etc/nginx/html
    depends_on:
      - api
      - frontend
      - backend
      - memcached
    ports:
      - 80:80
      - 443:443

  api:
    build:
      context: ./api
    image: jdsteam/sapawarga:1.0
    networks:
      - internal
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./api:/srv

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: jdsteam/sapawarga:1.0
    depends_on:
      - api
    networks:
      - internal
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: jdsteam/sapawarga:1.0
    depends_on:
      - api
    networks:
      - internal
    volumes:
      - ./frontend:/app

  # mobile:
  #   build:
  #     context: ./mobile
  #     dockerfile: Dockerfile.dev
  #   image: jdsteam/sapawarga:1.0
  #   depends_on:
  #     - api
  #   networks:
  #     - internal
  #   volumes:
  #     - ./mobile:/app

  database:
    image: mysql:5.7
    networks:
      - internal
    ports:
      - 3306:3306
    env_file:
      - .env

  memcached:
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge
