version: '3'
services:
  nginx:
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend-nginx:${VERSION}
    networks:
      - internal
    depends_on:
      - php-fpm
    ports:
      - 8000:8000

  php-fpm:
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend-php-fpm:${VERSION}
    networks:
      - internal
    depends_on:
      - database
    env_file:
      - .env-dev
    volumes:
      - ./api:/srv
      - /srv/vendor
      #- vol_storage:/srv/web/storage

  database:
    build:
      context: ./database
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend-mysql:${VERSION}
    networks:
      - internal
    ports:
      - 3306:3306
    env_file:
      - .env-dev
    volumes:
      - vol_mysql_data:/var/lib/mysql

  memcached:
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  vol_storage:
    driver: local
  vol_mysql_data:
    driver: local
