version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.test-api
    image: jdsteam/sapawarga-nginx:1.0
    networks:
      - internal
    volumes:
      - ./nginx:/etc/nginx/html
    depends_on:
      - api
      - memcached
    ports:
      - 80:80
      - 443:443

  api:
    build:
      context: ./api
    image: jdsteam/sapawarga-api:1.0
    networks:
      - internal
    depends_on:
      - database
    env_file:
      - .env-dev
    volumes:
      - ./api:/srv
      - /srv/vendor
      - vol_storage:/srv/web/storage

  database:
    image: mysql:5.7
    networks:
      - internal
    env_file:
      - .env-dev
    volumes:
      - vol_mysql_data:/var/lib/mysql

  memcached:
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  vol_storage:
    driver: local
  vol_mysql_data:
    driver: local