version: '3'
services:
  nginx:
    container_name: yii2_ngx_nginx
    image: jdsteam/yii2_ngx_nginx:1.0
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/html
    depends_on:
      - api
      - frontend
      - backend
      - memcached
    ports:
      - 80:80
      - 443:443

  api:
    container_name: yii2_ngx_api
    image: jdsteam/yii2_ngx_api:1.0
    networks:
      - internal
    env_file:
      - .env
    volumes:
      - ./api:/srv
      - /srv/vendor

  backend:
    container_name: yii2_ngx_backend
    image: jdsteam/yii2_ngx_backend:1.0
    depends_on:
      - api
    networks:
      - internal
    volumes:
      - ./backend/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/src:/app/src

  frontend:
    container_name: yii2_ngx_frontend
    image: jdsteam/yii2_ngx_frontend:1.0
    depends_on:
      - api
    networks:
      - internal
    volumes:
      - ./frontend/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/src:/app/src
      - ./frontend/node_modules:/app/node_modules

  memcached:
    container_name: yii2_ngx_memcached
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: overlay