version: '3'
services:
  nginx:
    container_name: yii2_nginx
    image: asatrya/yii2_nginx:latest
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/html
    depends_on:
      - api
      - frontend
      - backend
      - memcached
    ports:
      - 80:80
      - 443:443

  api:
    container_name: yii2_api
    image: asatrya/yii2_api:latest
    networks:
      - internal
    env_file:
      - .env
    volumes:
      - ./api:/var/www/app

  backend:
    container_name: yii2_backend
    image: asatrya/yii2_backend:prod
    depends_on:
      - api
    networks:
      - internal
    volumes:
      - ./backend/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/src:/app/src

  frontend:
    container_name: yii2_frontend
    image: asatrya/yii2_frontend:prod
    depends_on:
      - api
    networks:
      - internal
    volumes:
      - ./frontend/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/src:/app/src

  memcached:
    container_name: yii2_memcached
    image: memcached:latest
    networks:
      - internal

networks:
  internal:
    driver: overlay