apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sapawarga-memcached
  namespace: sapawarga
spec:
  template:
    metadata:
      labels:
        app: sapawarga-memcached
    spec:
      containers:
      - name: memcached
        image: memcached:latest
        ports:
          - containerPort: 11211