apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pv-claim
  namespace: sapawarga
  labels:
    app: sapawarga-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi