apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sapawarga-api
  namespace: sapawarga
  labels:
    app: sapawarga-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sapawarga-api
    spec:
      containers:
        - name: api
          image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend-api:%IMAGETAG%
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
          volumeMounts:
          - name: api-persistent-storage
            mountPath: /srv/web/storage
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: sapawarga-backend-config-env
                  key: MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: sapawarga-backend-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sapawarga-backend-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: sapawarga-backend-config-env
                  key: MYSQL_DATABASE
            - name: FCM_KEY
              valueFrom:
                configMapKeyRef:
                  name: sapawarga-backend-secret
                  key: FCM_KEY
            - name: COOKIE_VALIDATION_KEY
              valueFrom:
                secretKeyRef:
                  name: sapawarga-backend-secret
                  key: COOKIE_VALIDATION_KEY
            - name: CACHE_USE_MEMCACHED
              valueFrom:
                configMapKeyRef:
                  name: sapawarga-backend-config-env
                  key: CACHE_USE_MEMCACHED
            - name: CACHE_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: sapawarga-backend-config-env
                  key: CACHE_SERVERS
            - name: CACHE_PORT
              valueFrom:
                configMapKeyRef:
                  name: sapawarga-backend-config-env
                  key: CACHE_PORT
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: api-persistent-storage
        persistentVolumeClaim:
          claimName: api-pv-claim